### ISSUE TITLE
Allow Elm-like dsl with an implicit topic in scope

### ISSUE THREAD

**Issue by hejfelix** [armanbilge/calico#173]
Specifying the pipe for events is very powerful, but probably not necessary in the majority of cases. 

```scala 
button("-", onClick.as(Event.Decrement) --> outgoing.publish)
```

Where `outgoing` is a `Topic[F, Event]`. It would be nice if we could allow to skip that part to simply write:

```scala
button("-", onClick.as(Event.Decrement))
```

When we have an implicit `Topic[F, Event]` in scope. I realize this could become messy, so it could be provided as an opt-in or alternative syntax for the DSL

**Comment by armanbilge** [comment]
Firstly, if you are looking for an Elm-like experience, I strongly recommend you look at Tyrian :)

https://github.com/PurpleKingdomGames/tyrian

---

Otherwise, this sort of feature feels out-of-scope for Calico. However, I would be very supportive of a external library/framework that builds on Calico and offers this (and other Elm-like facilities).

To support this, all you need to do is put a custom `Modifier[F, HtmlElement, EventProp[F, E]]` into scope.

https://github.com/armanbilge/calico/blob/7f8d5860213f7a3a805c40cf2ba2da719237ca01/calico/src/main/scala/calico/html/Modifier.scala#L31-L37

Something like this:

```scala
given [F[_], N, E]: Modifier[F, N <: fs2.dom.Node[F], EventProp[F, E]](
  using sink: Topic[F, E]
) with
  def modify(prop: EventProp[F, E], node: N): Resource[F, Unit] =
    forPipeEventProp.modify(prop --> sink.publish, node)
```

**Comment by hejfelix** [comment]
Yeah I agree this might sit on the next level of abstraction or in the user's own code.
